### PR TITLE
Migrate off obsolete ‘cl’ library in favor of ‘cl-lib’

### PR DESCRIPTION
**Pull request by phst**

### CODE REVIEW

**Comment by rejeep** [comment]
Thanks for fixing, I added you as a collaborator, feel free to merge (same goes for the other PRs)

**Comment by phst** [comment]
> Thanks for fixing, I added you as a collaborator, feel free to merge (same goes for the other PRs)

Thanks!

**Comment by phst** [comment]
> > Thanks for fixing, I added you as a collaborator, feel free to merge (same goes for the other PRs)
> 
> Thanks!

Hmm, I still can't seem to merge the PR myself though. ("Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.")

**Comment by phst** [comment]
> > > Thanks for fixing, I added you as a collaborator, feel free to merge (same goes for the other PRs)
> > 
> > 
> > Thanks!
> 
> Hmm, I still can't seem to merge the PR myself though. ("Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.")

D'oh, I had to accept the invite first. Sorry for the noise.

**Pull request merged**
