### PR TITLE
docs(README.md): Document use with Eask

### PR DESCRIPTION
**Pull request by jcs090218**
Hi, I want to add document regarding the use with Eask.

Cask is basically unmaintained so I would like to introduce a new tool [Eask](https://github.com/emacs-eask/cli). It's very similar to Cask and syntax compatible. LMKWYT?

Thanks!

### CODE REVIEW

**Comment by dickmao** [comment]
ecukes, like its parent cask, is also unmaintained.

I'd give you commit rights if I could since ecukes is so far behind ERT (Elisp Regression Test) and current practices, that it's of little consequence what is written about or done to it (barring malware of course).

**Comment by jcs090218** [comment]
@dickmao Thanks for your answer!

Who is in charge of this repo? Since there is no public member presented in this org, I guess is `@rejeep`? I can help maintain the two packages in this org if they willing to let me do so.

cc @rejeep WDYT?

**Comment by rejeep** [comment]
@jcs090218 Hey, I added you as a collaborator!

**Comment by jcs090218** [comment]
@rejeep Awesome! Thank you so much! ♥️ 🚀 

I wonder if you can add me to the org? So I could navigate all repos under my profile. 

LMKWYT? Thanks!

**Comment by rejeep** [comment]
@jcs090218 Sure no problem, check if it worked

**Comment by jcs090218** [comment]
Oh! That was quick! Thank you so much! 🚀 ❤️ 😄 (It works!)

**Pull request merged**
